/*
 * Zenkipay API
 * Definition of technical specification of the product; Zenkipay is a gateway cryptocurrency payment system that allows merchant's to receive payments on their e-commerce portals. Unlike other platforms, Zenkipay ensures customer satisfaction through its payment process. guarantee deposit (delivered product and expected quality) to settle payment to the merchant, thus avoiding the loss of client assets due to online scams.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zenki.fi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.zenki.zenkipay.api.services;

import fi.zenki.zenkipay.api.ApiException;
import fi.zenki.zenkipay.api.model.Webhook;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for WebhooksApi
 */
@Ignore
public class WebhooksApiTest {

    private final WebhooksApi api = new WebhooksApi();

    
    /**
     * Event notifications for merchant
     *
     * Service that allows different events to be sent to the merchant.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendEventTest() throws ApiException {
        String svixId = null;
        String svixTimestamp = null;
        String svixSignature = null;
        String contentType = null;
        Webhook webhook = null;
        
        api.sendEvent(svixId, svixTimestamp, svixSignature, contentType, webhook);
        
        // TODO: test validations
    }
    
}
