/*
 * Zenkipay API
 * Definition of technical specification of the product; Zenkipay is a gateway cryptocurrency payment system that allows merchant's to receive payments on their e-commerce portals. Unlike other platforms, Zenkipay ensures customer satisfaction through its payment process. guarantee deposit (delivered product and expected quality) to settle payment to the merchant, thus avoiding the loss of client assets due to online scams.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zenki.fi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.zenki.zenkipay.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ErrorResponseValidationErrorsInner
 */
@JsonPropertyOrder({
  ErrorResponseValidationErrorsInner.JSON_PROPERTY_OBJECT_NAME,
  ErrorResponseValidationErrorsInner.JSON_PROPERTY_FIELD,
  ErrorResponseValidationErrorsInner.JSON_PROPERTY_MESSAGE
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-31T22:41:17.558143950Z[Etc/UTC]")
public class ErrorResponseValidationErrorsInner {
  public static final String JSON_PROPERTY_OBJECT_NAME = "objectName";
  private String objectName;

  public static final String JSON_PROPERTY_FIELD = "field";
  private String field;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  private String message;

  public ErrorResponseValidationErrorsInner() { 
  }

  public ErrorResponseValidationErrorsInner objectName(String objectName) {
    this.objectName = objectName;
    return this;
  }

   /**
   * Object name in the data structure where the error originates.
   * @return objectName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "createOrderTracking", required = true, value = "Object name in the data structure where the error originates.")
  @JsonProperty(JSON_PROPERTY_OBJECT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getObjectName() {
    return objectName;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObjectName(String objectName) {
    this.objectName = objectName;
  }


  public ErrorResponseValidationErrorsInner field(String field) {
    this.field = field;
    return this;
  }

   /**
   * Object field where it presents validation errors.
   * @return field
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "trackingId", required = true, value = "Object field where it presents validation errors.")
  @JsonProperty(JSON_PROPERTY_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getField() {
    return field;
  }


  @JsonProperty(JSON_PROPERTY_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setField(String field) {
    this.field = field;
  }


  public ErrorResponseValidationErrorsInner message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Error description caused by not passing some information validation.
   * @return message
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Tracking number is required.", required = true, value = "Error description caused by not passing some information validation.")
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(String message) {
    this.message = message;
  }


  /**
   * Return true if this ErrorResponse_validationErrors_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorResponseValidationErrorsInner errorResponseValidationErrorsInner = (ErrorResponseValidationErrorsInner) o;
    return Objects.equals(this.objectName, errorResponseValidationErrorsInner.objectName) &&
        Objects.equals(this.field, errorResponseValidationErrorsInner.field) &&
        Objects.equals(this.message, errorResponseValidationErrorsInner.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objectName, field, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorResponseValidationErrorsInner {\n");
    sb.append("    objectName: ").append(toIndentedString(objectName)).append("\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

