/*
 * Zenkipay API
 * Definition of technical specification of the product; Zenkipay is a gateway cryptocurrency payment system that allows merchant's to receive payments on their e-commerce portals. Unlike other platforms, Zenkipay ensures customer satisfaction through its payment process. guarantee deposit (delivered product and expected quality) to settle payment to the merchant, thus avoiding the loss of client assets due to online scams.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zenki.fi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.zenki.zenkipay.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * Summary of the amount paid in crypto currency by the buyer.
 */
@JsonPropertyOrder({
  MerchantEscrowConfig.JSON_PROPERTY_ORDER_TYPE,
  MerchantEscrowConfig.JSON_PROPERTY_SHOPPER_NOTIFICATION,
  MerchantEscrowConfig.JSON_PROPERTY_TIME_WAIT_TO_APPROVAL
})
@JsonTypeName("Merchant_escrowConfig")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-23T23:11:11.907534644Z[Etc/UTC]")
public class MerchantEscrowConfig {
  /**
   * Indicates the model for the product delivery or service delivery.  Possible values: * WITH_CARRIER    - If a courier is going to be used for the shipment and delivery of the product or service. * WITHOUT_CARRIER - If a courier is not going to be used for the shipment and delivery of the product or service. * MIXED           - If a courier is going to be used to send part of the products or services and another part is delivered without using a courier.
   */
  public enum OrderTypeEnum {
    WITH_CARRIER("WITH_CARRIER"),
    
    WITHOUT_CARRIER("WITHOUT_CARRIER"),
    
    MIXED("MIXED");

    private String value;

    OrderTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OrderTypeEnum fromValue(String value) {
      for (OrderTypeEnum b : OrderTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ORDER_TYPE = "orderType";
  private OrderTypeEnum orderType;

  public static final String JSON_PROPERTY_SHOPPER_NOTIFICATION = "shopperNotification";
  private Long shopperNotification;

  public static final String JSON_PROPERTY_TIME_WAIT_TO_APPROVAL = "timeWaitToApproval";
  private Long timeWaitToApproval;

  public MerchantEscrowConfig() {
  }

  public MerchantEscrowConfig orderType(OrderTypeEnum orderType) {
    
    this.orderType = orderType;
    return this;
  }

   /**
   * Indicates the model for the product delivery or service delivery.  Possible values: * WITH_CARRIER    - If a courier is going to be used for the shipment and delivery of the product or service. * WITHOUT_CARRIER - If a courier is not going to be used for the shipment and delivery of the product or service. * MIXED           - If a courier is going to be used to send part of the products or services and another part is delivered without using a courier.
   * @return orderType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OrderTypeEnum getOrderType() {
    return orderType;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderType(OrderTypeEnum orderType) {
    this.orderType = orderType;
  }


  public MerchantEscrowConfig shopperNotification(Long shopperNotification) {
    
    this.shopperNotification = shopperNotification;
    return this;
  }

   /**
   * Number of hours to wait for the merchant to notify Zenki that they have delivered the services to the shopper. Time is expressed in hours.
   * minimum: 0
   * @return shopperNotification
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHOPPER_NOTIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getShopperNotification() {
    return shopperNotification;
  }


  @JsonProperty(JSON_PROPERTY_SHOPPER_NOTIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShopperNotification(Long shopperNotification) {
    this.shopperNotification = shopperNotification;
  }


  public MerchantEscrowConfig timeWaitToApproval(Long timeWaitToApproval) {
    
    this.timeWaitToApproval = timeWaitToApproval;
    return this;
  }

   /**
   * Number of hours that Zenki will wait for confirmation from the buyer before approving the payment and releasing the funds to the merchant. Time is expressed in hours.
   * minimum: 0
   * @return timeWaitToApproval
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME_WAIT_TO_APPROVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTimeWaitToApproval() {
    return timeWaitToApproval;
  }


  @JsonProperty(JSON_PROPERTY_TIME_WAIT_TO_APPROVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeWaitToApproval(Long timeWaitToApproval) {
    this.timeWaitToApproval = timeWaitToApproval;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantEscrowConfig merchantEscrowConfig = (MerchantEscrowConfig) o;
    return Objects.equals(this.orderType, merchantEscrowConfig.orderType) &&
        Objects.equals(this.shopperNotification, merchantEscrowConfig.shopperNotification) &&
        Objects.equals(this.timeWaitToApproval, merchantEscrowConfig.timeWaitToApproval);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderType, shopperNotification, timeWaitToApproval);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantEscrowConfig {\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    shopperNotification: ").append(toIndentedString(shopperNotification)).append("\n");
    sb.append("    timeWaitToApproval: ").append(toIndentedString(timeWaitToApproval)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `orderType` to the URL query string
    if (getOrderType() != null) {
      try {
        joiner.add(String.format("%sorderType%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getOrderType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `shopperNotification` to the URL query string
    if (getShopperNotification() != null) {
      try {
        joiner.add(String.format("%sshopperNotification%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getShopperNotification()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `timeWaitToApproval` to the URL query string
    if (getTimeWaitToApproval() != null) {
      try {
        joiner.add(String.format("%stimeWaitToApproval%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTimeWaitToApproval()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

