/*
 * Zenkipay API
 * Definition of technical specification of the product; Zenkipay is a gateway cryptocurrency payment system that allows merchant's to receive payments on their e-commerce portals. Unlike other platforms, Zenkipay ensures customer satisfaction through its payment process. guarantee deposit (delivered product and expected quality) to settle payment to the merchant, thus avoiding the loss of client assets due to online scams.
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zenki.fi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.zenki.zenkipay.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MerchantEscrowConfig
 */
public class MerchantEscrowConfigTest {
    private final MerchantEscrowConfig model = new MerchantEscrowConfig();

    /**
     * Model tests for MerchantEscrowConfig
     */
    @Test
    public void testMerchantEscrowConfig() {
        // TODO: test MerchantEscrowConfig
    }

    /**
     * Test the property 'orderType'
     */
    @Test
    public void orderTypeTest() {
        // TODO: test orderType
    }

    /**
     * Test the property 'shopperNotification'
     */
    @Test
    public void shopperNotificationTest() {
        // TODO: test shopperNotification
    }

    /**
     * Test the property 'timeWaitToApproval'
     */
    @Test
    public void timeWaitToApprovalTest() {
        // TODO: test timeWaitToApproval
    }

}
