/*
 * Zenkipay API
 * Definition of technical specification of the product; Zenkipay is a gateway cryptocurrency payment system that allows merchant's to receive payments on their e-commerce portals. Unlike other platforms, Zenkipay ensures customer satisfaction through its payment process. guarantee deposit (delivered product and expected quality) to settle payment to the merchant, thus avoiding the loss of client assets due to online scams.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zenki.fi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.zenki.zenkipay.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.zenki.zenkipay.api.model.CryptoPayment;
import fi.zenki.zenkipay.api.model.OrderPaymentInfoCryptoLove;
import fi.zenki.zenkipay.api.model.OrderPaymentInfoExchangeRate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OrderPaymentInfo
 */
public class OrderPaymentInfoTest {
    private final OrderPaymentInfo model = new OrderPaymentInfo();

    /**
     * Model tests for OrderPaymentInfo
     */
    @Test
    public void testOrderPaymentInfo() {
        // TODO: test OrderPaymentInfo
    }

    /**
     * Test the property 'exchangeRate'
     */
    @Test
    public void exchangeRateTest() {
        // TODO: test exchangeRate
    }

    /**
     * Test the property 'cryptoLove'
     */
    @Test
    public void cryptoLoveTest() {
        // TODO: test cryptoLove
    }

    /**
     * Test the property 'cryptoPayment'
     */
    @Test
    public void cryptoPaymentTest() {
        // TODO: test cryptoPayment
    }

}
