/*
 * Zenkipay API
 * Definition of technical specification of the product; Zenkipay is a gateway cryptocurrency payment system that allows merchant's to receive payments on their e-commerce portals. Unlike other platforms, Zenkipay ensures customer satisfaction through its payment process. guarantee deposit (delivered product and expected quality) to settle payment to the merchant, thus avoiding the loss of client assets due to online scams.
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zenki.fi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fi.zenki.zenkipay.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.zenki.zenkipay.api.model.TrackingExternalCourier;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Tracking
 */
public class TrackingTest {
    private final Tracking model = new Tracking();

    /**
     * Model tests for Tracking
     */
    @Test
    public void testTracking() {
        // TODO: test Tracking
    }

    /**
     * Test the property 'zenkiTrackingId'
     */
    @Test
    public void zenkiTrackingIdTest() {
        // TODO: test zenkiTrackingId
    }

    /**
     * Test the property 'courierType'
     */
    @Test
    public void courierTypeTest() {
        // TODO: test courierType
    }

    /**
     * Test the property 'trackingId'
     */
    @Test
    public void trackingIdTest() {
        // TODO: test trackingId
    }

    /**
     * Test the property 'courierName'
     */
    @Test
    public void courierNameTest() {
        // TODO: test courierName
    }

    /**
     * Test the property 'externalCourier'
     */
    @Test
    public void externalCourierTest() {
        // TODO: test externalCourier
    }

}
